// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ_1A4R5AdM6Sd3ynEe4jfhb6r4kaCcFg',
    appId: '1:700829254681:web:7f1bfa66d92a821a5f5688',
    messagingSenderId: '700829254681',
    projectId: 'shopping-app-flutter-8be1c',
    authDomain: 'shopping-app-flutter-8be1c.firebaseapp.com',
    storageBucket: 'shopping-app-flutter-8be1c.firebasestorage.app',
    measurementId: 'G-YWN50WWB5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF80kK7KYf2r7EzfUJc-svE5ubppUtoYc',
    appId: '1:700829254681:android:9f2aee6c76ba8f4c5f5688',
    messagingSenderId: '700829254681',
    projectId: 'shopping-app-flutter-8be1c',
    storageBucket: 'shopping-app-flutter-8be1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7q44u1R-t7S8X_wTMRkY49vEKVJSgrdU',
    appId: '1:700829254681:ios:85da77312bd37c9f5f5688',
    messagingSenderId: '700829254681',
    projectId: 'shopping-app-flutter-8be1c',
    storageBucket: 'shopping-app-flutter-8be1c.firebasestorage.app',
    iosBundleId: 'com.example.shopAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7q44u1R-t7S8X_wTMRkY49vEKVJSgrdU',
    appId: '1:700829254681:ios:85da77312bd37c9f5f5688',
    messagingSenderId: '700829254681',
    projectId: 'shopping-app-flutter-8be1c',
    storageBucket: 'shopping-app-flutter-8be1c.firebasestorage.app',
    iosBundleId: 'com.example.shopAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ_1A4R5AdM6Sd3ynEe4jfhb6r4kaCcFg',
    appId: '1:700829254681:web:f508d55312972f9b5f5688',
    messagingSenderId: '700829254681',
    projectId: 'shopping-app-flutter-8be1c',
    authDomain: 'shopping-app-flutter-8be1c.firebaseapp.com',
    storageBucket: 'shopping-app-flutter-8be1c.firebasestorage.app',
    measurementId: 'G-TB8VN78Q7C',
  );
}
